 name: NeoSAPIAddons
 version: 1.0
 description: Various commands that SkillAPI is too bad to do by itself
 author: Neoblade298
 main: me.neoblade298.neosapiaddons.Main
 commands: 
  neosapiaddons:
    description: Base command for usage
    usage: /neosapiaddons [command] [player] [arg]