name: NeoResearch
main: me.neoblade298.base.Research
author: [Neoblade298]
depend: [MythicMobs]
version: 1.0
api-version: 1.16
commands:
   nr:
      description: Main command
      usage: /nr