name: NeoCollections
author: Neoblade298
main: me.neoblade298.neocollections.Main
version: 1.00
api-version: 1.14
commands:
  neocollections:
    description: Various usages of collections
    usage: /neocollections