name: NeoUno
main: me.neoblade298.neouno.Uno
author: [Neoblade298]
version: 1.5
api-version: 1.16
commands:
   uno:
      description: The base command
      usage: /uno
      permission: neouno.player