name: NeoInstruments
author: Neoblade298
main: me.neoblade298.neoinstruments.Main
version: 1.1
api-version: 1.13
commands:
  instruments:
    description: Various instrument commands
    usage: /instruments [args]