name: NeoInstruments
author: Neoblade298
main: me.neoblade298.neoinstruments.Main
version: 1.2
api-version: 1.13
commands:
  music:
    description: Various instruments commands
    usage: /music [args]