name: NeoInstruments
author: Neoblade298
main: me.neoblade298.neoinstruments.Main
version: 1.00
commands:
  instruments:
    description: Various instrument commands
    usage: /instruments [args]