# GPS-Quests configuration
enabled:
  citizens-to-interact: true
  citizens-to-kill: true
  locations-to-reach: true
  item-delivery-targets: true
  
# Enable GPS for a given quest. Enable the GPS for a
# specific stage by adding the stage's number to the
# list of numbers. Case sensitive quest name!
# Stage number starts from 0!
enabled-quests:
  ExampleQuest:
  - 1
  
# Same as enabled-quests, except specifically choose
# coordinates for the GPS to point to. Case sensitive
# quest name! Stage number starts from 0! All points are
# linearly connected.
overridden-quests:
  On the Trail of Corruption:
    '0':
    - 23.0 69.0 28.0
    - 24.0 67.0 9.0
    - 42.0 51.0 11.0
    - 42.0 51.0 44.0