name:  GPS-Quests
main: me.neoblade298.neoquestgps.Main
version: 1.2
api-version: 1.14
description: Navigate Quests objectives with GPS arrows
author: [PikaMug, Neoblade298]
depend: [GPS, Quests]
soft-depend: [Citizens]