# MLMC Tiered Items config
# %1 is the place of the durability
# %2 is the place of the max durability
custom-durability: "Durability: %1/%2"

# The permissions are:
# mlmctiereditems.get
# mlmctiereditems.give
# mlmctiereditems.help
# mlmctiereditems.reload
# mlmctiereditems.list
#
# Those are just so people can use the commands
# /mlmctier list
# /mlmctier get <tier name>
# /mlmctier give <player> <tier name>
# /mlmctier reload

sets:
    example_set:
    - "something"
    - "another tier"

# More messages for you
# The messages support the & as the color symbol(like always :D)
messages:
    reloaded-tiers: "&aTiers have been reloaded!"
    no-permissions: "&cYou do not have permission to use this command!"
    help: "&cValid arguments are &bgive <player> <tier> &c| &bget <tier> &c|&b list &c|&b reload"
    must-provide-name: "&cYou need to provide a player!"
    must-provide-tier: "&cYou need to provide a tier!"
    available-tiers: "&aValid tiers are:"
    no-console: "&cThis command must be run as a player!"
    no-tier: "&cThis tier/set does not exist!"
    not-online: "&b%p&c is not online right now!" # %p = player name
    gave-item: "&bYou have given an item of the &a%n &bto &a%p!" # %n = tier name, %p = player name
    got-item: "&bYou have recieved an item of the &a%n&b tier!" # %n = tier name