name: MLMCTieredItems
main: io.github.bananapuncher714.MLMCTieredItemsMain
version: 1.0
author: BananaPuncher714
api-version: 1.14
commands:
    mlmctier:
        description: Get an item from the available tiers