# Whether this server is an instance or not (the main server is not)
# If true, also give the name of the instance
Is_Instance: false
Instance_Name: "Instance1"

# Command to return a player to the main server
Return_Command: "bungeee send %player% s1"

# How long to wait before running the boss command, in seconds
Command_Delay: 20

# Configure all bosses here
# Cooldown in seconds
Bosses:
    Ratface:
        Cooldown: 1800
        Coordinates: "-650.5 4.0 -80.0 360.0 0.0"
        Command: "mythicmobs mobs spawn Ratface 1 Argyll,-633,5,-81"

# List of instances and the commands to teleport there
Instances:
  - s2