name: NeoStats
author: Neoblade298
main: me.neoblade298.neostats.Main
version: 1.00
api-version: 1.14
depend: [MythicMobs, SkillAPI]
commands:
  neostats:
    description: Various usages of stats
    usage: /neostats