name: NeoProfessions
author: Neoblade298
main: me.Neoblade298.NeoProfessions.Main
version: 1.0
api-version: 1.14
depend: [MythicMobs, SkillAPI, NeoGear, Vault]
commands:
  prof:
    description: Admin commands
    usage: /prof [args]
  blacksmith:
    description: Base command for blacksmiths
    usage: /blacksmith [args]
  mason:
    description: Base command for masons
    usage: /mason [args]
  stonecutter:
    description: Base command for stonecutters
    usage: /stonecutter [args]
  culinarian:
    description: Base command for culinarians
    usage: /culinarian [args]