name: NeoGoldRandomizer
author: Neoblade298
main: me.neoblade298.neogoldrandomizer.Main
version: 1.01
api-version: 1.14
depend: [NeoBossInstances]
commands:
  neogoldrandomizer:
    description: Does its job
    usage: /neogoldrandomizer [bossname] [min gold] [max gold]