

count: 0 # Don't change, this keeps track of vote count through restarts

general:
  voteparty: 1500 # number of votes to trigger the vote party
  countdown: 30 # number of seconds between achieving vote party and starting the party
  voteparty-command: # List of commands to run at the end of the countdown for the vote party
  - "mm mobs spawn VoteParty"
  - "say Neo is cool"
  
# Can use placeholder %player%, %votes%, %votesremaining%
notifications:
  # These announcements occur every x votes
  interval:
    num: 6
    message: "&4[&c&lMLMC&4] &e%votesremaining% &7votes left until the vote party!"
  # These announcements occur at exactly x votes
  specific:
    100: "&4[&c&lMLMC&4] &e%player% &7has voted! &e%votes% &7/ &e%votesrequired% &7votes for the vote party!"
    
# Can use placeholder %timeremaining%
countdown:
  10: "&4[&c&lMLMC&4] &e20 &7seconds until vote party begins at spawn!" # Run 10 seconds after the countdown begins