name: NeoReports
author: Neoblade298
main: me.neoblade298.neoreports.Main
version: 1.00
commands:
  neoreport:
    description: Base commands
    usage: /report
  neoreports:
    description: Base commands
    usage: /reports